export const DEFAULT_SCHEMA_FILE_NAME = '.env-sentinel';
export const DEFAULT_DOCS_FILE_NAME = 'CONFIGURATION.md';

export const DEFAULT_SCHEMA = `# .env-sentinel — generated by env-sentinel CLI
# Format: VAR_NAME=rule1|rule2[:arg]|rule3[:arg1,arg2]
# Docs: https://envsentinel.dev/docs

# ============================================================================
# @section Database
# @description Database connection settings
# ============================================================================

# @var Database server hostname
# @example localhost
DB_HOST=required

# @var Database server port
# @example 3306
DB_PORT=required|number

# @var Database username
# @example app_user
DB_USER=required

# @var Database password (keep secure!)
DB_PASS=required|secure|min:8

# ============================================================================
# @section Application
# @description Application configuration
# ============================================================================

# @var Application environment
# @example production
NODE_ENV=enum:development,production,test|default:"development"
`;
