export const DEFAULT_SCHEMA_FILE_NAME = '.env-sentinel';

export const DEFAULT_SCHEMA = `# .env-sentinel — generated by env-sentinel CLI
# Format: VAR_NAME=rule1|rule2[:arg]|rule3[:arg1,arg2]
# Docs: https://github.com/malyshev/env-sentinel

DB_HOST=required
DB_PORT=required|number
DB_USER=required
DB_PASS=required|secure|min:8
NODE_ENV=optional|enum:development,production,test
`;
